-- SQL Minor Project: Bike Store Sales & Inventory Analysis
-- Student Name: Darshan M
-- Internship: Unlox, Applied Data Science Internship

-- To create a Database
CREATE DATABASE BikeStore;

-- To use the desired Database
USE BikeStore;

-- To create table os stores
CREATE TABLE stores (
store_id INT PRIMARY KEY,
store_name VARCHAR(100),
phone VARCHAR(20),
email VARCHAR(100),
street VARCHAR(100),
city VARCHAR(50),
state VARCHAR(50),
zip_code VARCHAR(50)
);

-- To create table of customers
CREATE TABLE customers (
customer_id INT PRIMARY KEY,
first_name VARCHAR(50),
last_name VARCHAR(50),
phone VARCHAR(20),
email VARCHAR(50),
street VARCHAR(100),
city VARCHAR(50),
state VARCHAR(50),
zip_code VARCHAR(10)
);

-- To create table of orders
CREATE TABLE orders (
order_id INT PRIMARY KEY,
customer_id INT,
order_status INT,
order_date DATE,
required_date DATE,
shipped_date DATE,
store_id INT,
staff_id INT
);

-- To create table of order items
CREATE TABLE order_items (
order_id INT,
item_id INT,
product_id INT,
quantity INT,
list_price DECIMAL(10,2),
discount DECIMAL(10,2)
);

-- To create a table of products
CREATE TABLE products (
product_id INT PRIMARY KEY,
product_name VARCHAR(300),
brand_id INT,
category_id INT,
model_year INT,
list_price DECIMAL(10,2)
);

-- To create a table of brands
CREATE TABLE brands (
brand_id INT PRIMARY KEY,
brand_name VARCHAR(100)
);

-- To create a table of categories
CREATE TABLE categories (
category_id INT PRIMARY KEY,
category_name VARCHAR(100)
);

-- To create a table of stocks
CREATE TABLE stocks (
store_id INT,
product_id INT,
quantity INT 
);

-- To create a table of staffs
CREATE TABLE staffs (
staff_id INT PRIMARY KEY,
first_name VARCHAR(50),
last_name VARCHAR(50),
email VARCHAR(100),
phone VARCHAR(20),
active INT,
store_id INT,
manager_id INT
);

-- To show the tables in the database
SHOW TABLES;

-- To see the structure of each table
describe stores;
describe orders;
describe order_items;
describe products;
describe brands;
describe customers;
describe stocks;
describe categories;
describe staffs;


-- To see the data in the table
SELECT * FROM stores;
SELECT * FROM orders;
SELECT * FROM order_items;
SELECT * FROM products;
SELECT * FROM brands;
SELECT * FROM customers;
SELECT * FROM stocks;
SELECT * FROM categories;
SELECT * FROM staffs;

-- Key SQL Tasks

-- 1. Store Performance - Total revenue generated by each store
-- To make analysis of revenue in bike store
SELECT 
	s.store_name, 
	SUM(i.list_price * i.quantity * (1 -i.discount)) AS Total_Revenue
FROM stores s 
JOIN orders o ON s.store_id = o.store_id
JOIN order_items i ON o.order_id = i.order_id 
GROUP BY s.store_name 
ORDER BY Total_Revenue DESC;

-- 2. Product Popularity - Top 5 most sold products by quantity
SELECT 
	p.product_name, 
    SUM(oi.quantity) AS Total_Sold
FROM order_items oi
JOIN products p 
	ON oi.product_id = p.product_id
GROUP BY p.product_name
ORDER BY Total_Sold DESC
LIMIT 5;

-- 3. Customer Location - Customers who placed orders with store names
SELECT DISTINCT 
	c.first_name,
	c.last_name,
	c.city,
	s.store_name
FROM customers c
JOIN orders o 
	ON c.customer_id = o.customer_id
JOIN stores s 
	ON o.store_id = s.store_id
ORDER BY c.first_name;

-- 4. Brand Insights - Total number of products per brand
SELECT 
	b.brand_name, 
    COUNT(p.product_id) AS Total_Products
FROM brands b 
JOIN products p 
	ON b.brand_id = p.brand_id
GROUP BY b.brand_name
ORDER BY Total_Products DESC;

-- 5. Low Stock Alert - Products with zero quantity in stock
SELECT 
	p.product_name,
    s.store_name,
    st.quantity
FROM stocks st 
JOIN products p
	ON st.product_id = p.product_id
JOIN stores s 
	On st.store_id = s.store_id
WHERE st.quantity = 0
ORDER BY p.product_name;

